name: bSoul
version: '${project.version}'
main: net.danh.bsoul.bSoul
api-version: 1.13
authors: [ VoChiDanh ]
description: SoulPoints for RPG Server
softdepend:
  - PlaceholderAPI
  - MythicMobs
  - MMOItems
commands:
  soul:
    aliases:
      - sp